openapi: 3.0.0
info:
  title: GitHub Data API
  description: API documentation for saving and retrieving GitHub data.
  version: 1.0.0
servers:
  - url: https://githubapi-m5vf.onrender.com/
  - url: http://localhost:8000
paths:
  /github:
    post:
      summary: Save GitHub Data to MongoDB
      description: Save GitHub data to MongoDB.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
              example:
                "url": "https://api.github.com/users/mralexgray/repos"
      responses:
        '201':
          description: GitHub data saved successfully.
        '400':
          description: Invalid or empty GitHub data provided.
        '500':
          description: Internal server error.

  /github/{id}:
    get:
      summary: Retrieve Saved GitHub Data from MongoDB
      description: Retrieve GitHub data from MongoDB by repository ID.
      parameters:
        - in: path
          name: id
          required: true
          description: Repository ID
          schema:
            type: string
      responses:
        '200':
          description: Retrieved GitHub repository data.
        '404':
          description: GitHub repository not found.
        '500':
          description: Internal server error.
